// @vitest-environment jsdom
//
// One writer per Gating-ML file, and both of the importer's readings of it from that one answer:
// the edge rule of its rectangles (writerRectangleBounds) and whether its coordinates are scale
// values or stored ones (gatingMlGainConvention). The merge of #344 and #348 carried two
// identifications with different marks, so a file could be one writer to the edge rule and
// another, or none, to the gain.
import { describe, expect, it } from "vitest";
import { gatingMLWriter, writerRectangleBounds } from "./gatingml";
import { gatingMlGainConvention } from "./gatingmlGain";

const HEAD = '<gating:Gating-ML xmlns:gating="http://www.isac-net.org/std/Gating-ML/v2.0/gating" ' +
  'xmlns:data-type="http://www.isac-net.org/std/Gating-ML/v2.0/datatypes">';
const DIMS = '<gating:dimension gating:min="1" gating:max="2"><data-type:fcs-dimension data-type:name="FSC-A"/></gating:dimension>';
const doc = (info: string, gateAttrs = "", gateInfo = ""): string =>
  `${HEAD}${info}<gating:RectangleGate gating:id="G" ${gateAttrs}>${gateInfo}${DIMS}</gating:RectangleGate></gating:Gating-ML>`;
const ci = (body: string) => `<data-type:custom_info>${body}</data-type:custom_info>`;

const CASES: { name: string; xml: string; writer: string }[] = [
  { name: "GateLab's about line", xml: doc(ci("<cytobank><about>Gating-ML 2.0 export from GateLab (standard / re-importable)</about></cytobank>")), writer: "gatelab" },
  { name: "GateLabR's scales block", xml: doc(ci("<gatelabr_scales><definition>{}</definition></gatelabr_scales>")), writer: "gatelab" },
  // GateLab's standard format until 2026-09 and GateLabR's: not a Gating-ML 2.0 element.
  { name: "a GatingHierarchy element", xml: `${HEAD}<gating:GatingHierarchy/><gating:RectangleGate gating:id="G">${DIMS}</gating:RectangleGate></gating:Gating-ML>`, writer: "gatelab" },
  { name: "CytoML", xml: doc(ci("<info>Gating-ML 2.0 export generated by R/flowCore/CytoML</info><CytoML-version>2.16.0</CytoML-version><cytobank><experiment_number></experiment_number></cytobank>")), writer: "cytoml" },
  { name: "flowUtils", xml: doc(ci("<info>Gating-ML 2.0 export generated by R/flowUtils/flowCore</info>")), writer: "flowutils" },
  { name: "Cytobank's about line", xml: doc(ci("<cytobank><about>Gating-ML 2.0 export of Cytobank experiment number 1.</about></cytobank>")), writer: "cytobank" },
  { name: "FlowJo, every attribute", xml: doc("", 'eventsInside="1" annoOffsetX="0" annoOffsetY="0" tint="#000000" isTinted="0" lineWeight="Normal" userDefined="1"'), writer: "flowjo" },
  // FlowJo's polygon attributes without eventsInside and userDefined: still FlowJo's, which no
  // other writer puts on a gate element.
  { name: "FlowJo, a grid polygon's attributes only", xml: doc("", 'quadId="-1" gateResolution="256"'), writer: "flowjo" },
  // GateLab's standard format writes a cytobank block in every gate; without the root's about line
  // (or GateLab's own blocks) nothing says Cytobank wrote the file.
  { name: "a cytobank block in a gate, and nothing at the root", xml: doc("", "", ci("<cytobank><name>G</name></cytobank>")), writer: "unidentified" },
  { name: "FlowKit, which writes no mark", xml: doc(""), writer: "unidentified" },
];

describe("a Gating-ML file's writer decides both its edge rule and its gain convention", () => {
  for (const c of CASES) {
    it(`${c.name}: ${c.writer}`, () => {
      const root = new DOMParser().parseFromString(c.xml, "application/xml").documentElement;
      const writer = gatingMLWriter(root);
      expect(writer).toBe(c.writer);
      const unidentified = writer === "unidentified";
      expect(writerRectangleBounds(writer)).toBe(unidentified ? "half-open" : "closed");
      expect(gatingMlGainConvention(c.xml)).toBe(unidentified ? "scale" : "stored");
    });
  }
});
