// gatingmlWriter.ts — who wrote a Gating-ML document, and the two readings that follow from it.
//
// One identification serves both questions the importer asks of a file's writer: the edge rule of
// its rectangles (gatingml.ts, setRectangleRule; models.ts, RectangleBounds) and whether its
// coordinates are Gating-ML scale values or the stored values GateLab gates (gatingmlGain.ts,
// $PnG). Until 2026-09 each question had its own function with its own marks: a CytoML file was
// "cytoml" to the edge rule and "cytobank" to the gain, a FlowJo export was FlowJo to one only with
// both eventsInside and userDefined and to the other with any of nine attributes, and a file whose
// gates carried a cytobank block but whose root said nothing was unidentified to one and Cytobank's
// to the other. A writer is now one answer, and each rule is a function of that answer.

import { GATINGML_EDGE_RULE_TAG, GATINGML_RECTANGLES_TAG } from "./rectangleRecord";
import type { RectangleBounds } from "./models";

/**
 * Who wrote a Gating-ML document, as far as the document itself says.
 *
 * Every mark below was read off real files, never assumed:
 *   - GateLab and GateLabR: "Gating-ML 2.0 export from GateLab" (or "GateLabR") in the
 *     document's custom_info <about>, and the gatelabr_scales block, in both formats since
 *     2026-07 (the concordance experiment's exports); a GatingHierarchy element, which GateLab's
 *     standard format wrote until 2026-09 and GateLabR's still does; from 2026-09 also GateLab's
 *     gatelab_format, gatelab_edge_rule and gatelab_rectangles blocks (rectangleRecord.ts).
 *   - CytoML (gatingset_to_cytobank): <CytoML-version> and "generated by R/flowCore/CytoML" in
 *     the document's custom_info (CytoML 2.16.0, written 2026-09-24). It also writes a <cytobank>
 *     block, so it is told apart from Cytobank first.
 *   - flowUtils (write.gatingML): "generated by R/flowUtils/flowCore" in the document's
 *     custom_info <info> (the FR-FCM-Z69Z deposit's files).
 *   - Cytobank: "Gating-ML 2.0 export of Cytobank experiment number ..." in custom_info <about>
 *     (three Cytobank exports of 2026-08-24 and 2026-09-07). A cytobank block inside a gate's
 *     custom_info is not enough: GateLab's standard format writes one in every gate, and such a
 *     file that has lost its root custom_info is on scale values, not Cytobank's stored ones.
 *   - FlowJo's own Gating-ML export: FlowJo's un-namespaced attributes on the gate elements
 *     themselves (eventsInside, userDefined, annoOffsetX, gateResolution and the rest; FlowJo 10.10
 *     exports of a 24-sample workspace), which the schema does not define and no other writer here
 *     uses. The .wsp converter copies FlowJo's gate elements, and so carries them too; its
 *     rectangles are marked anyway, and its documents are never read for a gain.
 * FlowKit 1.3.1 writes no mark of any kind (export_gatingml, 2026-09-24): its files are
 * unidentified, and follow the standard, which is FlowKit's own rule.
 */
export type GatingMLWriter = "gatelab" | "cytoml" | "flowutils" | "cytobank" | "flowjo" | "unidentified";

/** Attributes FlowJo writes on the gate elements of its Gating-ML export, outside any namespace. */
const FLOWJO_GATE_ATTRIBUTES = new Set([
  "eventsInside", "annoOffsetX", "annoOffsetY", "tint", "isTinted", "lineWeight", "userDefined",
  "quadId", "gateResolution",
]);

function firstChild(el: Element | null, name: string): Element | null {
  if (!el) return null;
  for (let c = el.firstElementChild; c; c = c.nextElementSibling) if (c.localName === name) return c;
  return null;
}

export function gatingMLWriter(root: Element): GatingMLWriter {
  const ci = firstChild(root, "custom_info");
  const text = (el: Element | null): string => (el?.textContent ?? "").trim();
  const about = ci ? text(firstChild(firstChild(ci, "cytobank") ?? ci, "about")) : "";
  if (/^Gating-ML 2\.0 export from GateLab/.test(about)) return "gatelab";
  if (ci && ["gatelabr_scales", "gatelab_format", GATINGML_RECTANGLES_TAG, GATINGML_EDGE_RULE_TAG]
    .some((tag) => firstChild(ci, tag))) return "gatelab";
  if (firstChild(root, "GatingHierarchy")) return "gatelab";
  const info = ci ? text(firstChild(ci, "info")) : "";
  if ((ci && firstChild(ci, "CytoML-version")) || /\bCytoML\b/.test(info)) return "cytoml";
  if (/\bflowUtils\b/.test(info)) return "flowutils";
  if (/^Gating-ML 2\.0 export of Cytobank experiment\b/.test(about)) return "cytobank";
  for (let el = root.firstElementChild; el; el = el.nextElementSibling) {
    if (!el.localName.endsWith("Gate")) continue;
    for (const attr of Array.from(el.attributes)) {
      if (!attr.namespaceURI && FLOWJO_GATE_ATTRIBUTES.has(attr.localName)) return "flowjo";
    }
  }
  return "unidentified";
}

/** gatingMLWriter of a document given as text; "unidentified" when it does not parse. */
export function gatingMLWriterOf(xmlText: string): GatingMLWriter {
  const doc = new DOMParser().parseFromString(xmlText, "application/xml");
  if (doc.getElementsByTagName("parsererror").length) return "unidentified";
  return gatingMLWriter(doc.documentElement);
}

/**
 * The edge rule a writer's rectangles follow, and where that was established.
 *
 *   - closed, GateLab and GateLabR up to 0.8.3: every rectangle was evaluated min <= x <= max
 *     (gates.ts before 2026-09; GateLabR gate_engine.R gate_mask_rectangle). A file GateLab
 *     writes now records each rectangle's rule (rectangleRecord.ts), and states the rule of one
 *     without a record, the standard's (GATINGML_EDGE_RULE_TAG); both win over this.
 *   - closed, flowUtils and CytoML: flowUtils reads a Gating-ML rectangle, and writes one, as a
 *     flowCore rectangleGate, and CytoML evaluates gates with cytolib; both hold both edges
 *     (measured 2026-09-24 on an integer grid: flowCore 2.16.0 filter() and a cytolib 2.16.0
 *     GatingSet each keep 35 of the 35 events in [2, 8] x [3, 7], where half-open keeps 24).
 *     flowCore, but not cytolib, holds nothing with a zero-width rectangle (gatingml.ts,
 *     flowCoreHoldsNothing).
 *   - closed, FlowJo: FlowJo's own counts side with both edges in (WSP_RECT_BOUNDS_TAG).
 *   - closed, Cytobank, by default rather than by measurement: no event lies on the upper edge
 *     of any Cytobank rectangle in the data with Cytobank's own results (the concordance
 *     datasets), so its rule is unmeasured, and a Cytobank file keeps the reading it had.
 *   - half-open, anything unidentified: Gating-ML 2.0 section 5.1.1, and FlowKit's rule.
 */
export function writerRectangleBounds(writer: GatingMLWriter): RectangleBounds {
  return writer === "unidentified" ? "half-open" : "closed";
}

/**
 * Whether a writer's coordinates are Gating-ML scale values (stored value / $PnG) or the stored
 * values GateLab gates, where the file carries no GateLab mark saying which (gatingmlGain.ts):
 *   - stored, GateLab and GateLabR before the mark: both wrote GateLab's coordinates unconverted;
 *   - stored, Cytobank: as GateLab has always read it; whether Cytobank divides by $PnG is not
 *     established (no Cytobank export of a file with a gain other than 1 on a gated channel);
 *   - stored, FlowJo, flowUtils and CytoML, a default (2026-09, for David to confirm): FlowJo gates
 *     stored values in a .wsp and writes the same coordinates into its Gating-ML export; flowUtils
 *     and CytoML write flowCore and cytolib gates, which read.FCS's default gates on stored values.
 *     None has been measured on a file with a gain other than 1;
 *   - scale values, anything unidentified, as the standard defines them.
 * To read FlowJo, flowUtils or CytoML files as the standard defines instead, return "scale" for
 * them here.
 */
export function writerGainConvention(writer: GatingMLWriter): "scale" | "stored" {
  return writer === "unidentified" ? "scale" : "stored";
}
