import {
  validateAndCanonicalizeCompensationMatrix,
} from "../engine/compensationProfile";
import {
  createCompensationBaselineProfile,
} from "../engine/compensationProfileRecord";
import {
  adoptedRProfile,
  authoritativeRProfile,
  R_CYTOF_NNLS_SOLVER_VERSION,
  R_EXTERNAL_PRECOMPUTED_SOLVER_VERSION,
} from "./compensationContract";
import {
  CYTOF_NNLS_SOLVER_VERSION,
  DEFAULT_CYTOF_NNLS_SETTINGS,
} from "../engine/cytofCompensationEngine";

async function browserCytofProfile() {
  const matrix = validateAndCanonicalizeCompensationMatrix({
    sourceChannels: ["A", "B"],
    receiverChannels: ["A", "B"],
    matrix: [
      [1, 0.1],
      [0.2, 1],
    ],
  }, "cytof-spillover");
  if (!matrix.ok) throw new Error("fixture matrix failed");
  return createCompensationBaselineProfile({
    kind: "cytof-spillover",
    method: "nnls",
    solverVersion: CYTOF_NNLS_SOLVER_VERSION,
    solverSettings: DEFAULT_CYTOF_NNLS_SETTINGS,
    matrix: matrix.value,
    includedChannels: ["A", "B"],
  }, {
    profileId: "browser-profile",
    name: "Test matrix",
    createdAt: "2026-07-25T00:00:00.000Z",
    origin: {
      type: "uploaded",
      fileName: "matrix.csv",
      format: "csv",
      sourceColumnHeader: "",
    },
  });
}

describe("authoritativeRProfile", () => {
  it("retains the matrix identity but truthfully changes the solver identity", async () => {
    const browser = await browserCytofProfile();
    const hosted = await authoritativeRProfile(browser);

    expect(hosted.profileId).not.toBe(browser.profileId);
    expect(hosted.matrixHash).toBe(browser.matrixHash);
    expect(hosted.profileHash).not.toBe(browser.profileHash);
    expect(hosted.scientific.solverVersion)
      .toBe(R_CYTOF_NNLS_SOLVER_VERSION);
    expect(hosted.scientific.matrix).toEqual(browser.scientific.matrix);
    expect(hosted.scientific.includedChannels)
      .toEqual(browser.scientific.includedChannels);
    // Cross-language oracle generated by GateLabR's canonical R serializer.
    expect(hosted.matrixHash).toBe(
      "sha256:bd7ea5f09c9f4357e98f326bcf3fd325248390daca971df5fe5724d1a209cb98",
    );
    expect(hosted.profileHash).toBe(
      "sha256:63edaf41f68c925e0b5f988b73fb1f7929290c0db99a2bc16d74ddc1cbb8de48",
    );
  });

  it("does not fork an already authoritative R profile", async () => {
    const hosted = await authoritativeRProfile(
      await authoritativeRProfile(await browserCytofProfile()),
    );
    await expect(authoritativeRProfile(hosted)).resolves.toEqual(hosted);
  });
});

describe("adoptedRProfile", () => {
  it("preserves the matrix while labelling the solve as external", async () => {
    const browser = await browserCytofProfile();
    const adopted = await adoptedRProfile(browser);

    expect(adopted.profileId).not.toBe(browser.profileId);
    expect(adopted.matrixHash).toBe(browser.matrixHash);
    expect(adopted.profileHash).not.toBe(browser.profileHash);
    expect(adopted.scientific.solverVersion)
      .toBe(R_EXTERNAL_PRECOMPUTED_SOLVER_VERSION);
    expect(adopted.provenance?.estimationMethod)
      .toBe("External precomputed assay");
    expect(adopted.provenance?.applicabilityNote)
      .toContain("without recomputation");
    // Cross-language oracle generated by GateLabR's canonical R serializer.
    expect(adopted.profileHash).toBe(
      "sha256:d7785bb209109dcb0c9c540c469190c9f08d323e77830dbb3716d32b6ddc781c",
    );
    await expect(adoptedRProfile(adopted)).resolves.toEqual(adopted);
  });
});
