// @vitest-environment jsdom
//
// Gating-ML written by FlowJo or flowUtils is read on stored values by default, not multiplied by
// $PnG as a standard file is, and the import says so where a gated channel has a gain. Synthetic
// file: FSC-A with $PnG 5, SSC-A with none.

import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { FcsFile } from "./engine/fcs";

vi.mock("./plots/GatingPlot", () => ({
  DEFAULT_GATING_FONT_SIZES: { tick: 9, axis: 12, title: 12, gate: 10 },
  GatingPlot: () => <div data-testid="gating-plot" />,
}));

function gainFcs(): FcsFile {
  // FSC-A 100..1000 in steps of 100. A gate from 150 to 650 holds 5 events on stored values
  // (200-600), and 3 when its bounds are scale values restated × 5 (750-3250: 800-1000).
  const fsc = Float32Array.from({ length: 10 }, (_, i) => (i + 1) * 100);
  return {
    version: "FCS3.1",
    nEvents: 10,
    instrument: "flow",
    keywords: { $P1G: "5" },
    channels: [
      { index: 0, name: "FSC-A", marker: null, bits: 32, range: 262144, gain: 5 },
      { index: 1, name: "SSC-A", marker: null, bits: 32, range: 262144 },
    ],
    columns: [fsc, Float32Array.from({ length: 10 }, () => 500)],
    spillover: null,
  };
}
vi.mock("./engine/fcs", async (importOriginal) => {
  const actual = await importOriginal<typeof import("./engine/fcs")>();
  return { ...actual, parseFcs: () => gainFcs() };
});

import App from "./App";

const HEAD =
  '<?xml version="1.0" encoding="UTF-8"?>\n<gating:Gating-ML xmlns:gating="http://www.isac-net.org/std/Gating-ML/v2.0/gating"' +
  ' xmlns:data-type="http://www.isac-net.org/std/Gating-ML/v2.0/datatypes">';
const RECT = (attrs: string) => `
  <gating:RectangleGate ${attrs} gating:id="R1">
    <gating:dimension gating:min="150" gating:max="650"><data-type:fcs-dimension data-type:name="FSC-A" /></gating:dimension>
    <gating:dimension gating:min="0" gating:max="1000"><data-type:fcs-dimension data-type:name="SSC-A" /></gating:dimension>
  </gating:RectangleGate></gating:Gating-ML>`;
const FLOWJO = `${HEAD}${RECT('eventsInside="1" annoOffsetX="0" annoOffsetY="0" tint="#000000" isTinted="0" lineWeight="Normal" userDefined="1" quadId="-1" gateResolution="256"')}`;
const FLOWUTILS = `${HEAD}<data-type:custom_info><info>Gating-ML 2.0 export generated by R/flowUtils/flowCore</info></data-type:custom_info>${RECT("")}`;
const STANDARD = `${HEAD}${RECT("")}`;

let root: Root;
let host: HTMLDivElement;
let uuid = 0;
beforeEach(() => {
  vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT", true);
  vi.stubGlobal("crypto", { randomUUID: () => `00000000-0000-4000-8000-${String(++uuid).padStart(12, "0")}` });
  host = document.createElement("div");
  document.body.appendChild(host);
  root = createRoot(host);
});
afterEach(() => {
  act(() => root.unmount());
  host.remove();
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
  uuid = 0;
});

async function settle(): Promise<void> {
  await act(async () => { await new Promise((resolve) => setTimeout(resolve, 20)); });
}

async function loadAndImport(xml: string): Promise<void> {
  act(() => root.render(<App />));
  const fcsInput = [...host.querySelectorAll<HTMLInputElement>('input[type="file"][accept=".fcs"]')]
    .find((candidate) => !candidate.hasAttribute("webkitdirectory"))!;
  const bytes = Uint8Array.from([1]);
  const fcs = new File([bytes], "D1.fcs");
  Object.defineProperty(fcs, "arrayBuffer", { value: async () => bytes.buffer.slice(0) });
  Object.defineProperty(fcsInput, "files", { configurable: true, value: [fcs] });
  await act(async () => { fcsInput.dispatchEvent(new Event("change", { bubbles: true })); });
  await settle();
  const xmlInput = host.querySelector<HTMLInputElement>('input[accept=".xml,.wsp,.cef"]')!;
  const file = new File([xml], "gates.xml", { type: "text/xml" });
  Object.defineProperty(file, "text", { value: async () => xml });
  Object.defineProperty(file, "arrayBuffer", { value: async () => new TextEncoder().encode(xml).buffer });
  Object.defineProperty(xmlInput, "files", { configurable: true, value: [file] });
  await act(async () => { xmlInput.dispatchEvent(new Event("change", { bubbles: true })); });
  await settle();
  await settle();
  const importButton = [...host.querySelectorAll<HTMLButtonElement>("button")].find((b) => b.textContent?.trim() === "Import");
  if (importButton) {
    act(() => importButton.click());
    await settle();
    await settle();
  }
}

const gateRow = () => [...host.querySelectorAll(".pop-row")].map((r) => r.textContent?.replace(/\s+/g, " ").trim()).find((t) => t?.includes("R1"));

describe("importing Gating-ML onto a file with a gain", () => {
  it("reads FlowJo's Gating-ML on stored values and says so", async () => {
    await loadAndImport(FLOWJO);
    expect(host.textContent).toContain("read on stored values, as FlowJo writes Gating-ML; $PnG not applied (FSC-A ×5)");
    expect(host.textContent).not.toContain("converted from Gating-ML scale values");
    expect(gateRow()).toContain("5(50% pnt");
  });

  it("reads flowUtils' Gating-ML on stored values and says so", async () => {
    await loadAndImport(FLOWUTILS);
    expect(host.textContent).toContain("read on stored values, as flowUtils writes Gating-ML; $PnG not applied (FSC-A ×5)");
    expect(gateRow()).toContain("5(50% pnt");
  });

  it("still reads a standard file on scale values, stored value / $PnG", async () => {
    await loadAndImport(STANDARD);
    expect(host.textContent).toContain("converted from Gating-ML scale values by $PnG (FSC-A ×5)");
    expect(gateRow()).toContain("3(30% pnt");
  });
});
